### ISSUE TITLE
Need same color for all the searched & highlighted text (for multiple search terms)

### ISSUE THREAD

**Issue by vijucalicut** [stephanrauh/extended-pdf-viewer-showcase#48]
Is there any option to set same single color for all the searched & highlighted text (for multiple search terms)?

**Comment by stephanrauh** [comment]
Well, it's CSS, so you can override it:

```css
.textLayer .highlight.color0 {
  background-color: rgba(180, 0, 170, 0.4);
}
.textLayer .highlight.color0.selected {
  background-color: rgb(180, 0, 170);
}

.textLayer .highlight.color1 {
  background-color: rgb(0, 100, 0, 0.4);
}
.textLayer .highlight.color1.selected {
  background-color: rgb(0, 100, 0);
}

.textLayer .highlight.color2 {
  background-color: rgb(0, 0, 255, 0.4);
}
.textLayer .highlight.color2.selected {
  background-color: rgb(0, 0, 255);
}

.textLayer .highlight.color3 {
  background-color: rgb(255, 0, 0, 0.4);
}
.textLayer .highlight.color3.selected {
  background-color: rgb(255, 0, 0);
}

textLayer .highlight.color4 {
  background-color: rgb(255, 94, 0, 0.4);
}
.textLayer .highlight.color4.selected {
  background-color: rgb(255, 94, 0);
}
```
